### ISSUE TITLE
Conflicts when installing packages

### ISSUE THREAD

**Issue by viajerus** [3dgeo-heidelberg/etrainee_heidelberg_2024#1]
Hello, 
I've tried to create a new environment using the etrainee_m1.yml file (with mamba) and I got the following error(s):

![image](https://github.com/3dgeo-heidelberg/etrainee_heidelberg_2024/assets/63015973/5b08b68e-9bed-4dd4-8e1f-f8350984782b)
I am using Ubuntu 22.04.

Best, 
Daniel Abanto

**Comment by bhoefle-3dgeo** [comment]
Dear Daniel,
thanks a lot for this hint. Andreas provided also a cross-platform compatible version for us. The content is:

```
name: etrainee_m1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - earthengine-api
  - eemont
  - geemap
  - pygis
  - wxee
  - scikit-learn
  - stackstac
  - xarrayutils
  - hvplot
  - datashader
  - xmovie
  - laspy
  - vaex
  - seaborn
  - ca-certificates
  - openssl
```

Could you please test it and in if it works shortly comment and close the issue.

Thanks

**Comment by viajerus** [comment]
Thanks! This worked smooth :)
