### ISSUE TITLE
Broken Link course book

### ISSUE THREAD

**Issue by patupar** [3dgeo-heidelberg/etrainee_heidelberg_2024#2]
https://knowledge.dea.ga.gov.au/notebooks/Frequently_used_code/Opening_GeoTIFFs_NetCDFs/#Multiple-GeoTIFFs 
Theme 1 -> Tutorial 1 under Section "Loading many files of an image time series[¶](https://3dgeo-heidelberg.github.io/etrainee_heidelberg_2024/module1/01_principles_of_remote_sensing_time_series/T1_S2_xarray.html#loading-many-files-of-an-image-time-series)" is broken

**Comment by bhoefle-3dgeo** [comment]
Will be changed in main repository of ETRAINEE.
